while (true) fun foo() {} // [ERROR] Expected '(' after 'fun' in anonymous function at 1:18.
